--- 
abstract: Perl interface to hiveminder.com
author: Shawn M Moore, C<< <sartak at gmail.com> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-Hiveminder
no_index: 
  directory: 
    - inc
    - t
requires: 
  Net::Jifty: 0.02
  Number::RecordLocator: 0
version: 0.01
